export const IPC_TAB_GROUP_INVOKE = {
  CREATE_TAB_GROUP: "CREATE_TAB_GROUP",
  DELETE_TAB_GROUP: "DELETE_TAB_GROUP",
  RENAME_TAB_GROUP: "RENAME_TAB_GROUP",
  SET_TAB_GROUP_COLOR: "SET_TAB_GROUP_COLOR",
  ADD_TAB_TO_GROUP: "ADD_TAB_TO_GROUP",
  REMOVE_TAB_FROM_GROUP: "REMOVE_TAB_FROM_GROUP",
  GET_TAB_GROUPS: "GET_TAB_GROUPS",
  TOGGLE_TAB_GROUP_COLLAPSE: "TOGGLE_TAB_GROUP_COLLAPSE",
  REORDER_TABS_IN_GROUP: "REORDER_TABS_IN_GROUP",
  HIDE_GROUP: "HIDE_GROUP",
  UNHIDE_GROUP: "UNHIDE_GROUP",
  OPEN_GROUP_TAB: "OPEN_GROUP_TAB",
} as const;

export const IPC_TAB_GROUP_EMIT = {
  SHOW_TAB_GROUP_CONTEXT_MENU: "SHOW_TAB_GROUP_CONTEXT_MENU",
} as const;

export const IPC_TAB_GROUP_RENDERER_EVENT = {
  TAB_GROUP_UPDATED: "TAB_GROUP_UPDATED",
  TAB_GROUP_SHOW_CONTEXT_MENU: "TAB_GROUP_SHOW_CONTEXT_MENU",
  TAB_GROUP_HIDE: "TAB_GROUP_HIDE",
} as const;
