export const IPC_INVOKE_CHANNEL = {
  GET_TABS: "GET_TABS",
  CREATE_TAB: "CREATE_TAB",
  GET_TAB: "GET_TAB",
  GET_USER_INTERFACE: "GET_USER_INTERFACE",
  CLOUD_SAVE: "CLOUD_SAVE",
  INTERFACE_SAVE: "INTERFACE_SAVE",
  GET_USERSCRIPTS: "GET_USERSCRIPTS",
  SAVE_USERSCRIPT: "SAVE_USERSCRIPT",
  IMPORT_USERSCRIPT: "IMPORT_USERSCRIPT",
  DELETE_USERSCRIPT: "DELETE_USERSCRIPT",
  TOGGLE_USERSCRIPT: "TOGGLE_USERSCRIPT",
  VAULT_LIST: "VAULT_LIST",
  VAULT_ADD: "VAULT_ADD",
  VAULT_UPDATE: "VAULT_UPDATE",
  VAULT_DELETE: "VAULT_DELETE",
  VAULT_FILL: "VAULT_FILL",
  VAULT_SELECT_CREDENTIAL: "VAULT_SELECT_CREDENTIAL",
  VAULT_CONFIRM_SAVE: "VAULT_CONFIRM_SAVE",
  VAULT_OPEN_MANAGER: "VAULT_OPEN_MANAGER",
  USERSCRIPT_OPEN_MANAGER: "USERSCRIPT_OPEN_MANAGER",
  TRANSLATE_GET_PREFERENCE: "TRANSLATE_GET_PREFERENCE",
  TRANSLATE_SAVE_PREFERENCE: "TRANSLATE_SAVE_PREFERENCE",
  TRANSLATE_DETECT_LANGUAGE: "TRANSLATE_DETECT_LANGUAGE",
  TRANSLATE_PAGE: "TRANSLATE_PAGE",
  TRANSLATE_SELECTION: "TRANSLATE_SELECTION",
  TRANSLATE_OPEN_MANAGER: "TRANSLATE_OPEN_MANAGER",
  TRANSLATE_GET_SELECTION_HISTORY: "TRANSLATE_GET_SELECTION_HISTORY",
  SPOTLIGHT_OPEN: "SPOTLIGHT_OPEN",
  SPOTLIGHT_CLOSE: "SPOTLIGHT_CLOSE",
  SEARCH_PAGE: "SEARCH_PAGE",
  FOUND_IN_PAGE: "FOUND_IN_PAGE",
  STOP_SEARCH: "STOP_SEARCH",
} as const;

export const IPC_EMIT_CHANNEL = {
  SHOW_VIEW_BY_ID: "SHOW_VIEW_BY_ID",
  VIEW_RESPONSIVE: "VIEW_RESPONSIVE",
  SHOW_VIEW: "SHOW_VIEW",
  HIDE_VIEW: "HIDE_VIEW",
  UPDATE_VIEW_SIZE: "UPDATE_VIEW_SIZE",
  VIEW_CHANGE_URL: "VIEW_CHANGE_URL",
  ON_BACKWARD: "ON_BACKWARD",
  FORWARD_TAB: "FORWARD_TAB",
  ON_CLOSE_TAB: "ON_CLOSE_TAB",
  TOGGLE_DEV_TOOLS: "TOGGLE_DEV_TOOLS",
  ON_RELOAD: "ON_RELOAD",
  CLOSE_APP: "CLOSE_APP",
  REQUEST_PIP: "REQUEST_PIP",
  TOGGLE_BOOKMARK: "TOGGLE_BOOKMARK",
  SPOTLIGHT_OPEN: "SPOTLIGHT_OPEN",
  SPOTLIGHT_CLOSE: "SPOTLIGHT_CLOSE",
  OPEN_TAB_BY_ID: "OPEN_TAB_BY_ID",
} as const;

export const IPC_RENDERER_EVENT = {
  CREATE_TAB: "CREATE_TAB",
  GET_TABS: "GET_TABS",
  SYNC: "SYNC",
  SEARCH: "SEARCH",
  TOGGLE_DEV_TOOLS: "TOGGLE_DEV_TOOLS",
  ON_RELOAD: "ON_RELOAD",
  FAVICON_UPDATED: "FAVICON_UPDATED",
  TITLE_UPDATED: "TITLE_UPDATED",
  LOADING: "LOADING",
  URL_CHANGED: "URL_CHANGED",
  VAULT_CREDENTIAL_DETECTED: "VAULT_CREDENTIAL_DETECTED",
  FILL_PASSWORD_REQUEST: "FILL_PASSWORD_REQUEST",
  TRANSLATE_LANGUAGE_DETECTED: "TRANSLATE_LANGUAGE_DETECTED",
  TRANSLATE_SELECTION_AVAILABLE: "TRANSLATE_SELECTION_AVAILABLE",
  OPEN_TAB_BY_ID: "OPEN_TAB_BY_ID",
} as const;

export type IPCInvokeChannel = (typeof IPC_INVOKE_CHANNEL)[keyof typeof IPC_INVOKE_CHANNEL];
export type IPCEmitChannel = (typeof IPC_EMIT_CHANNEL)[keyof typeof IPC_EMIT_CHANNEL];
export type IPCRendererEventChannel = (typeof IPC_RENDERER_EVENT)[keyof typeof IPC_RENDERER_EVENT];

// 4. Additional suggestions
// - Virtual list: If tabs grows large (50+), replace the flat map with react-window or @tanstack/virtual to skip DOM work for off-screen items
// - Debounce search: For fast typers, debounce the useMemo computation by ~50ms
// - Fuzzy search: Use fuse.js for typo-tolerant tab matching instead of simple includes()
// - Persist window position: Save spotlight window bounds between opens
// - Escape to close: Already works, but you could also add Escape listener on the backdrop div
// - will-change: transform on the animated panel to hint GPU compositing